AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an IAM role with an ExternalId for cross-account access.

Parameters:
  ExternalId:
    Type: String
    Description: External ID used to ensure the request is coming from the intended party
    MinLength: 1
    MaxLength: 256
    AllowedPattern: '^[a-zA-Z0-9+=,.@_-]*$'
    ConstraintDescription: ExternalId must be 1-256 characters long and consist of alphanumeric characters and select special characters (+=,.@_-).

Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: CrossAccountRole
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal: 
              AWS: "arn:aws:iam::123456789012:root"  # Replace with the account ID of the trusted account
            Action: 
              - "sts:AssumeRole"
            Condition: 
              StringEquals: 
                sts:ExternalId: !Ref ExternalId
      Policies: 
        - PolicyName: AllowMoreReadForProwler
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action: 
                  - "account:Get*"
                  - "appstream:Describe*"
                  - "appstream:List*"
                  - "backup:List*"
                  - "cloudtrail:GetInsightSelectors"
                  - "codeartifact:List*"
                  - "codebuild:BatchGet*"
                  - "cognito-idp:GetUserPoolMfaConfig"
                  - "dlm:Get*"
                  - "drs:Describe*"
                  - "ds:Get*"
                  - "ds:Describe*"
                  - "ds:List*"
                  - "dynamodb:GetResourcePolicy"
                  - "ec2:GetEbsEncryptionByDefault"
                  - "ec2:GetInstanceMetadataDefaults"
                  - "ecr:Describe*"
                  - "ecr:GetRegistryScanningConfiguration"
                  - "elasticfilesystem:DescribeBackupPolicy"
                  - "glue:GetConnections"
                  - "glue:GetSecurityConfiguration*"
                  - "glue:SearchTables"
                  - "lambda:GetFunction*"
                  - "logs:FilterLogEvents"
                  - "lightsail:GetRelationalDatabases"
                  - "macie2:GetMacieSession"
                  - "s3:GetAccountPublicAccessBlock"
                  - "shield:DescribeProtection"
                  - "shield:GetSubscriptionState"
                  - "securityhub:BatchImportFindings"
                  - "securityhub:GetFindings"
                  - "ssm:GetDocument"
                  - "ssm-incidents:List*"
                  - "support:Describe*"
                  - "tag:GetTagKeys"
                  - "wellarchitected:List*"
                Resource: 
                  - "*"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/SecurityAudit"
        - "arn:aws:iam::aws:policy/job-function/ViewOnlyAccess"

Outputs:
  RoleArn:
    Description: ARN of the created IAM role
    Value: !GetAtt CrossAccountRole.Arn
